#!/bin/bash

ENV=neural_operator
CONFIG="configs/inference_global.yaml"

# Initialize conda in the current shell session
eval "$(conda shell.bash hook)"

if [[ "$CONDA_DEFAULT_ENV" != "$ENV" ]]; then
    echo "Activating environment..."
    conda activate $ENV
    echo "Activated $ENV"
fi

echo "Start Inferencing..."
python cli/inference_global.py --config="$CONFIG"


