#!/bin/bash

ENV=neural_operator
CONFIG="configs/local.yaml"

# Initialize conda in the current shell session
eval "$(conda shell.bash hook)"

if [[ "$CONDA_DEFAULT_ENV" != "$ENV" ]]; then
    echo "Activating environment..."
    conda activate $ENV
    echo "Activated $ENV"
fi

echo "Start Training..."
python cli/train_local.py --config="$CONFIG"


